window.SAT_DATA = {
  verified: "2026-09-06",
  sources: [
    {id:"jo-moe",nameAr:"وزارة التربية والتعليم الأردنية — الدبلوم الأمريكي",nameEn:"Jordan Ministry of Education — American Diploma",url:"https://moe.gov.jo/sites/default/files/ss_brnmj_hsd_.pdf"},
    {id:"est",nameAr:"EST الأردن — الأسئلة الشائعة",nameEn:"EST Jordan — FAQ",url:"https://jordan.estests.com/faqs"},
    {id:"ap",nameAr:"College Board — اختبارات AP",nameEn:"College Board — AP",url:"https://apstudents.collegeboard.org/"},
    {id:"precalc",nameAr:"College Board — AP Precalculus",nameEn:"College Board — AP Precalculus",url:"https://apstudents.collegeboard.org/courses/ap-precalculus/assessment"},
    {id:"sat",nameAr:"College Board — Digital SAT",nameEn:"College Board — Digital SAT",url:"https://satsuite.collegeboard.org/"},
    {id:"toefl",nameAr:"ETS — TOEFL iBT",nameEn:"ETS — TOEFL iBT",url:"https://www.ets.org/toefl/test-takers/ibt/scores/understand-scores.html"},
    {id:"etec",nameAr:"هيئة تقويم التعليم والتدريب",nameEn:"Education & Training Evaluation Commission",url:"https://etec.gov.sa/"},
    {id:"egypt",nameAr:"ادرس في مصر — وزارة التعليم العالي",nameEn:"Study in Egypt — Ministry of Higher Education",url:"https://study-in-egypt.gov.eg/"},
    {id:"cnu",nameAr:"مجلس الجامعات الخاصة والأهلية المصري",nameEn:"Egyptian Council of Private Universities",url:"https://cnu.mohesr.gov.eg/"},
    {id:"alfaisal",nameAr:"جامعة الفيصل — القبول",nameEn:"Alfaisal University — Admissions",url:"https://admissions.alfaisal.edu/"},
    {id:"tbilisi",nameAr:"جامعة تبليسي الطبية الحكومية",nameEn:"Tbilisi State Medical University",url:"https://tsmu.edu/ts/"},
    {id:"ju-rec",nameAr:"وزارة التعليم العالي الأردنية — الجامعات غير الأردنية المعترف بها",nameEn:"Jordan Ministry of Higher Education — Recognized Foreign Institutions",url:"https://rce.mohe.gov.jo/RecognizedUniversities"}
  ],
  exams: [
    {id:"diploma",titleAr:"الدبلوم الأمريكي",titleEn:"American Diploma",kind:"credential",validity:"none",countries:["jordan","sa-public","sa-private","egypt","georgia"],summaryAr:"الشهادة المدرسية الأساسية. يجب التحقق من اعتماد المدرسة والبرنامج وإكمال متطلبات التخرج والتصديقات.",summaryEn:"The core school credential. Verify school/program accreditation, graduation credits and attestations.",source:"jo-moe",grade:"10–12"},
    {id:"ap-bio",titleAr:"AP Biology",titleEn:"AP Biology",kind:"subject",validity:"none",countries:["jordan","sa-private","egypt","georgia"],summaryAr:"اختبار أحياء متقدم. هدف التخطيط للطب 4 أو 5، وليس ضمان قبول.",summaryEn:"Advanced biology exam. A 4–5 is a planning target for medicine, not an admission guarantee.",source:"ap",grade:"11–12"},
    {id:"ap-chem",titleAr:"AP Chemistry",titleEn:"AP Chemistry",kind:"subject",validity:"none",countries:["jordan","sa-private","egypt","georgia"],summaryAr:"اختبار كيمياء متقدم. هدف التخطيط للطب 4 أو 5.",summaryEn:"Advanced chemistry exam. A 4–5 is a planning target for medicine.",source:"ap",grade:"11–12"},
    {id:"ap-precalc",titleAr:"AP Precalculus",titleEn:"AP Precalculus",kind:"subject",validity:"none",countries:["jordan"],summaryAr:"جزء من التشكيلة الأردنية المقترحة. لا يُجمع مع EST II Math لاستكمال المعادلة.",summaryEn:"Part of the proposed Jordan combination. Do not combine it with EST II Math for equivalency completion.",source:"precalc",grade:"10–11"},
    {id:"sat",titleAr:"Digital SAT",titleEn:"Digital SAT",kind:"general",validity:"institution",countries:["sa-private","egypt","georgia"],summaryAr:"SAT الحالي رقمي؛ ليس اختباراً منفصلاً. لا يلزم لمسار الأردن الأساسي لكنه يوسع الخيارات.",summaryEn:"The current SAT is digital—not a separate test. It is not needed for the Jordan core but can broaden options.",source:"sat",grade:"11–12"},
    {id:"est1",titleAr:"EST I",titleEn:"EST I",kind:"general",validity:"3-result",countries:["egypt"],summaryAr:"أضفه فقط إذا أصبح خيار مصر جاداً وبعد تأكيد القواعد الرسمية في سنة التقديم.",summaryEn:"Add only if Egypt becomes serious and the application-year rules confirm it.",source:"est",grade:"12"},
    {id:"est2-bio",titleAr:"EST II Biology",titleEn:"EST II Biology",kind:"subject",validity:"3-result",countries:["jordan","egypt"],summaryAr:"جزء من المسار الأردني المقترح. 750+ هدف تخطيطي، لا حد قبول مضمون.",summaryEn:"Part of the proposed Jordan path. 750+ is a planning target, not a guaranteed admission threshold.",source:"est",grade:"11–12"},
    {id:"est2-chem",titleAr:"EST II Chemistry",titleEn:"EST II Chemistry",kind:"subject",validity:"3-result",countries:["jordan","egypt"],summaryAr:"جزء من المسار الأردني المقترح. يحتاج التوقيت والقواعد إلى إعادة تحقق.",summaryEn:"Part of the proposed Jordan path. Timing and rules must be reverified.",source:"est",grade:"11–12"},
    {id:"toefl",titleAr:"TOEFL iBT",titleEn:"TOEFL iBT",kind:"language",validity:"2-test",countries:["sa-private","georgia"],summaryAr:"إثبات لغة؛ صلاحيته سنتان من تاريخ الاختبار، لذلك يُفضّل قرب التقديم.",summaryEn:"English proof; valid for two years from the test date, so take it closer to application.",source:"toefl",grade:"11–12"},
    {id:"qudurat",titleAr:"القدرات العامة",titleEn:"General Aptitude (Qudurat)",kind:"national",validity:"verify",countries:["sa-public"],summaryAr:"مرتبط بمسار السعودية الحكومية وبأهلية فئة القبول؛ الصلاحية والنسب تحتاج تحققاً وقت التقديم.",summaryEn:"Relevant to Saudi public admission and eligibility category; validity and weighting need application-year verification.",source:"etec",grade:"11–12"},
    {id:"tahsili",titleAr:"الاختبار التحصيلي",titleEn:"Achievement Test (Tahsili)",kind:"national",validity:"verify",countries:["sa-public"],summaryAr:"متطلب محتمل للقبول الحكومي؛ لا يعني أهلية أو قبولاً مضموناً لغير السعودي.",summaryEn:"A likely public-admission requirement; it does not guarantee eligibility or admission for a non-Saudi applicant.",source:"etec",grade:"12"}
  ],
  destinations: [
    {id:"jordan",nameAr:"الأردن",nameEn:"Jordan",class:"jordan",status:"verified",summaryAr:"المسار الأساسي: معادلة الدبلوم الأمريكي أولاً، ثم قبول الطب التنافسي.",summaryEn:"Core path: American Diploma equivalency first, then competitive medical admission.",required:["diploma","ap-bio","ap-chem","ap-precalc","est2-bio","est2-chem"],recommended:[],source:"jo-moe",noteAr:"تشكيلة 3 AP + 2 EST II مبنية على التعليمات الحالية؛ أعِد التحقق في 2028/2029.",noteEn:"The 3 AP + 2 EST II combination reflects current guidance; reverify in 2028/2029."},
    {id:"sa-public",nameAr:"السعودية الحكومية",nameEn:"Saudi Public",class:"saudi",status:"needs-reverification",summaryAr:"خيار مشروط بالأهلية والجنسية/الإقامة وفئة قبول غير السعوديين.",summaryEn:"Conditional on eligibility, nationality/residency and non-Saudi admission category.",required:["diploma","qudurat","tahsili"],recommended:[],source:"etec",noteAr:"ليس قبولاً مضموناً لحسان بصفته أردنياً؛ تحقّق من الجامعة والدورة المحددة.",noteEn:"Not guaranteed for Hassan as a Jordanian; verify the specific university and cycle."},
    {id:"sa-private",nameAr:"السعودية الخاصة",nameEn:"Saudi Private",class:"saudi2",status:"institution-specific",summaryAr:"كل جامعة تضع شروطها؛ راجع الفيصل والمعرفة وغيرها بصورة منفصلة.",summaryEn:"Each university sets its own rules; check Alfaisal, Almaarefa and others individually.",required:["diploma"],recommended:["sat","ap-bio","ap-chem","toefl"],source:"alfaisal",noteAr:"لا تعمم GPA أو SAT أو اللغة من جامعة على أخرى.",noteEn:"Do not generalize GPA, SAT or language rules across universities."},
    {id:"egypt",nameAr:"مصر",nameEn:"Egypt",class:"egypt",status:"needs-reverification",summaryAr:"المواد والـcredits والاختبارات وقواعد الوافدين تتغير حسب دورة التنسيق.",summaryEn:"Subjects, credits, tests and international-student rules depend on the admission cycle.",required:["diploma"],recommended:["est1","est2-bio","est2-chem"],source:"egypt",noteAr:"لا نفترض إمكان دمج Digital SAT مع EST II؛ يلزم تأكيد رسمي سنة التقديم.",noteEn:"Do not assume Digital SAT can be combined with EST II; confirm officially in the application year."},
    {id:"georgia",nameAr:"جورجيا",nameEn:"Georgia",class:"georgia",status:"institution-specific",summaryAr:"الشهادة واللغة B2 ومتطلبات الأحياء/الكيمياء أو المقابلة تختلف حسب الجامعة.",summaryEn:"Diploma, B2 English and biology/chemistry or interview requirements vary by university.",required:["diploma"],recommended:["toefl","ap-bio","ap-chem"],source:"tbilisi",noteAr:"تحقق من اعتراف الجامعة والبرنامج في الأردن عند بدء الدراسة، لا من إعلان مكتب قبول.",noteEn:"Verify Jordanian recognition of the university and program when study begins—not through an agent ad."}
  ],
  timeline: [
    {grade:"10",year:"2026/2027",titleAr:"قاعدة الانطلاق",titleEn:"Launch Base",tasksAr:["قوِّ الرياضيات والعلوم والإنجليزية","خطّط لمواد AP دون استعجال الاختبارات الخارجية","لا تقدّم TOEFL الآن؛ صلاحيته سنتان"],tasksEn:["Strengthen math, science and English","Plan AP subjects without rushing external tests","Do not take TOEFL yet; it lasts two years"]},
    {grade:"11",year:"2027/2028",titleAr:"مدار العلوم",titleEn:"Science Orbit",tasksAr:["AP Biology و/أو AP Chemistry حسب الاستعداد","أول EST II مناسب","محاولة جدية أولى في Digital SAT إذا بقيت الخيارات الدولية"],tasksEn:["AP Biology and/or Chemistry when ready","First suitable EST II","First serious Digital SAT attempt if wider options remain"]},
    {grade:"12",year:"2028/2029",titleAr:"بوابة القبول",titleEn:"Admission Gateway",tasksAr:["أكمل AP وEST II المتبقية","قدّم TOEFL قرب نافذة التقديم","أعد التحقق من كل القواعد وجهّز التصديقات"],tasksEn:["Complete remaining AP and EST II","Take TOEFL near the application window","Reverify every rule and prepare attestations"]}
  ]
};
