#!/usr/bin/env python3
"""Generate the static Arabic pages (ar/index.html, ar/publications.html) from the English pages.

How translations are stored (in the English HTML files):
  data-ar="..."            Arabic text for the element's content
  data-ar-<attribute>="..." Arabic value for an attribute (aria-label, content, href, placeholder, alt, lang, dir, ...)

Run from the repository root after editing index.html or publications.html:
  python3 tools/build-arabic.py
Then commit the regenerated files in ar/ together with your change.
No third-party packages are needed.
"""
import html
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAGES = {
    "index.html": {
        "out": "ar/index.html",
        "canonical_en": "https://dromaia.github.io/",
        "canonical_ar": "https://dromaia.github.io/ar/",
    },
    "publications.html": {
        "out": "ar/publications.html",
        "canonical_en": "https://dromaia.github.io/publications.html",
        "canonical_ar": "https://dromaia.github.io/ar/publications.html",
    },
}

TEXT_RE = re.compile(r'<([a-zA-Z][a-zA-Z0-9]*)((?:\s[^>]*?)?)\sdata-ar="([^"]*)"([^>]*)>(.*?)</\1\s*>', re.S)
TAG_RE = re.compile(r"<([a-zA-Z][a-zA-Z0-9]*)(\s[^>]*)?>", re.S)
AR_ATTR_RE = re.compile(r'\sdata-ar-([a-zA-Z-]+)="([^"]*)"')
STRIP_RE = re.compile(r'\sdata-(?:ar|en)(?:-[a-zA-Z-]+)?="[^"]*"')
URL_RE = re.compile(r'\b(href|src)="([^"]*)"')
SKIP_PREFIXES = ("http://", "https://", "//", "/", "#", "mailto:", "tel:", "data:", "javascript:")


def translate_text(source: str) -> str:
    """Replace the content of every element that carries data-ar."""

    def swap(match: re.Match) -> str:
        tag, before, arabic, after, _content = match.groups()
        return f"<{tag}{before} data-ar=\"{arabic}\"{after}>{arabic}</{tag}>"

    return TEXT_RE.sub(swap, source)


def translate_attributes(source: str) -> str:
    """Apply every data-ar-<attribute> to its attribute (replacing or adding it)."""

    def swap(match: re.Match) -> str:
        tag, attrs = match.group(1), match.group(2) or ""
        pairs = AR_ATTR_RE.findall(attrs)
        if not pairs:
            return match.group(0)
        for name, value in pairs:
            existing = re.compile(r'(\s' + re.escape(name) + r'=")[^"]*(")')
            if existing.search(attrs):
                attrs = existing.sub(lambda m: f"{m.group(1)}{value}{m.group(2)}", attrs, count=1)
            else:
                attrs = f'{attrs} {name}="{value}"'
        return f"<{tag}{attrs}>"

    return TAG_RE.sub(swap, source)


def strip_translation_attributes(source: str) -> str:
    return STRIP_RE.sub("", source)


def rewrite_relative_urls(source: str) -> str:
    """The Arabic pages live one folder down: assets move to ../, links between pages stay local."""

    def swap(match: re.Match) -> str:
        attr, value = match.groups()
        if value.startswith(SKIP_PREFIXES) or value.endswith(".html") or ".html#" in value or ".html?" in value or value == "":
            return match.group(0)
        return f'{attr}="../{value}"'

    return URL_RE.sub(swap, source)


def fix_structured_data(source: str, canonical_en: str, canonical_ar: str) -> str:
    """Point the page-level JSON-LD entity at the Arabic URL and language."""
    for spaced in (f'"url": "{canonical_en}"', f'"url":"{canonical_en}"'):
        if spaced in source:
            source = source.replace(spaced, spaced.replace(canonical_en, canonical_ar), 1)
            break
    source = source.replace('"inLanguage": "en"', '"inLanguage": "ar"').replace('"inLanguage":"en"', '"inLanguage":"ar"')
    return source


def build(page: str, spec: dict) -> None:
    source = (ROOT / page).read_text(encoding="utf-8")
    out = translate_text(source)
    out = translate_attributes(out)
    out = strip_translation_attributes(out)
    out = rewrite_relative_urls(out)
    out = fix_structured_data(out, spec["canonical_en"], spec["canonical_ar"])
    banner = f"<!-- Generated by tools/build-arabic.py from ../{page}. Edit the English file and rebuild; do not edit this file by hand. -->\n"
    out = out.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + banner, 1)
    target = ROOT / spec["out"]
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(out, encoding="utf-8")
    untranslated = len(re.findall(r'data-ar', out))
    print(f"{page} -> {spec['out']} ({len(out) // 1024} KB, leftover data-ar attributes: {untranslated})")


if __name__ == "__main__":
    for page, spec in PAGES.items():
        build(page, spec)
    sys.exit(0)

