#!/usr/bin/env python3
"""Write the instruction file every AI coding tool reads automatically when it opens this repository.

Single source: isp/CLAUDE.md (rules) and isp/README.md (full description). Run after editing either of them:
    python3 tools/sync-ai-instructions.py
Files written (all generated, do not edit by hand):
    CLAUDE.md                         Claude Code (loaded automatically; imports the two sources)
    AGENTS.md                         OpenAI Codex, Jules, Aider, Zed, Cursor and other tools using AGENTS.md
    GEMINI.md                         Gemini CLI / Gemini Code Assist
    .github/copilot-instructions.md   GitHub Copilot
    .cursor/rules/isp.mdc             Cursor (always applied)
    .windsurfrules                    Windsurf
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
rules = (ROOT / 'isp/CLAUDE.md').read_text(encoding='utf-8').strip()
readme = (ROOT / 'isp/README.md').read_text(encoding='utf-8').strip()

HEAD = """<!-- Generated by tools/sync-ai-instructions.py from isp/CLAUDE.md and isp/README.md. Do not edit by hand. -->
# Instructions for AI tools working on this repository

This repository is the GitHub Pages site https://dromaia.github.io/ (branch `main`, no build step).
- Main academic site (`index.html`, `publications.html`): see `README.md`; English is the source, the Arabic pages are
  generated by `python3 tools/build-arabic.py`.
- `/isp/` is the **IS Teaching Timetable** tool. Before any change to it, follow the rules below and use the full
  description that follows them. After changing `isp/CLAUDE.md` or `isp/README.md`, run
  `python3 tools/sync-ai-instructions.py` so every tool sees the same text.
"""
full = f"{HEAD}\n---\n\n{rules.replace('# Instructions for anyone (AI or human) changing `/isp/`', '## Rules for changing `/isp/`', 1)}\n\n---\n\n{readme.replace('# IS Teaching Timetable (`/isp/`)', '## About `/isp/` — IS Teaching Timetable', 1)}\n"

claude = f"""{HEAD}
The two files below are loaded automatically:

@isp/CLAUDE.md
@isp/README.md
"""
outputs = {
    'CLAUDE.md': claude,
    'AGENTS.md': full,
    'GEMINI.md': full,
    '.github/copilot-instructions.md': full,
    '.cursor/rules/isp.mdc': "---\ndescription: Rules and description of the site and the /isp/ timetable tool\nalwaysApply: true\n---\n\n" + full,
    '.windsurfrules': full,
}
for name, text in outputs.items():
    p = ROOT / name
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding='utf-8')
    print('wrote', name)
